export default {
  OKR_EDIT_BUTTON_CLICKED: 'OKR_EDIT_BUTTON_CLICKED',
  OKR_CHANGED: 'OKR_CHANGED',
  OKR_RATING_CHANGED: 'OKR_RATING_CHANGED',


  // Actually used actions
  OKR_COMMENT_BUTTON_CLICKED: 'OKR_COMMENT_BUTTON_CLICKED',
  OKR_ADD_NEW_OBJECTIVE: 'OKR_ADD_NEW_OBJECTIVE',
  OKR_ADD_NEW_KEY_RESULT: 'OKR_ADD_NEW_KEY_RESULT'
}
