export default {
  OKR_EDIT_BUTTON_CLICKED: 'OKR_EDIT_BUTTON_CLICKED',
  OKR_CHANGED: 'OKR_CHANGED',
  OKR_RATING_CHANGED: 'OKR_RATING_CHANGED',

  // Actually used actions
  OKR_COMMENT_BUTTON_CLICKED: 'OKR_COMMENT_BUTTON_CLICKED',
  OKR_ADD_NEW_OBJECTIVE: 'OKR_ADD_NEW_OBJECTIVE',
  OKR_OBJECTIVE_CHANGED: 'OKR_OBJECTIVE_CHANGED',
  OKR_DELETE_OBJECTIVE: 'OKR_DELETE_OBJECTIVE',

  // Key Result actions
  OKR_ADD_NEW_KEY_RESULT: 'OKR_ADD_NEW_KEY_RESULT',
  OKR_DELETE_KEY_RESULT: 'OKR_DELETE_KEY_RESULT',
  OKR_KEY_RESULT_CHANGED: 'OKR_KEY_RESULT_CHANGED',
  OKR_KEY_RESULT_RATE_CHANGED: 'OKR_KEY_RESULT_RATE_CHANGED',

  // Delete confirmed
  OKR_CONFIRM_DELETE: 'OKR_CONFIRM_DELETE',

  // Modal forms
  OKR_LINK: 'OKR_LINK',
  OKR_SAVE_LINK: 'OKR_SAVE_LINK',
  OKR_ADD_TAGS: 'OKR_ADD_TAGS',
  OKR_SAVE_TAGS: 'OKR_SAVE_TAGS'
}
